[package]
name = 'h3sampling'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.90.0'

[lib]
crate-type = [ 'rlib', 'staticlib' ]
name = 'h3sampling'

[[bin]]
name = 'document'
path = 'document.rs'

[dependencies]
extendr-api = '0.9.0'
rand = { version = '0.8.5', default-features = false }
rand_pcg = '0.3.1'
geo = '0.28'
h3o = { version = '0.9', features = ['geo'] }
wkb = '0.9'
geo-traits = { version = '0.3', features = ['geo-types'] }

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[profile.dev]
opt-level = 1
