# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_h3sampling_wrappers", use_symbols = TRUE, package_name = "h3sampling")

#' @usage NULL
#' @useDynLib h3sampling, .registration = TRUE
NULL

#' Generate a GRTS (Generalized Random Tessellation Stratified) sample of H3
#' cell indices covering a polygon.
#'
#' # Arguments
#' * `wkb_bytes`  – Study area geometry encoded as Well-Known Binary.
#' * `res`        – H3 resolution (0 = coarsest, 15 = finest).
#' * `containment`– One of `"intersect"`, `"centroid"`, `"boundary"`, `"covers"`.
#' * `n`          – Desired sample size.
#' * `global_seed`– Reproducibility seed (passed as f64 from R; values above
#'                  2^53 lose precision — prefer seeds within that range).
#'
#' # Returns
#' A vector of H3 cell identifiers as lowercase hexadecimal strings, ordered
#' by their GRTS address (i.e. the spatially balanced visiting order).
generate_grts_sample <- function(wkb_bytes, res, containment, n, global_seed) .Call(wrap__generate_grts_sample, wkb_bytes, res, containment, n, global_seed)


# nolint end
