# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_h3sampling_wrappers", use_symbols = TRUE, package_name = "h3sampling")

#' @usage NULL
#' @useDynLib h3sampling, .registration = TRUE
NULL

#' geometry -> coverage
#' @noRd
h3_coverage <- function(wkb_bytes, res, containment) .Call(wrap__h3_coverage, wkb_bytes, res, containment)

#' Generate a GRTS sample (Internal C-ABI function)
#'
#' Geometry -> Coverage -> Sample
#' This function is wrapped by `h3_grts()` in R and should not be
#' called directly by the user.
#' Generate a GRTS (Generalized Random Tessellation Stratified) sample of H3
#' cell indices covering a polygon.
#'
#' # Arguments
#' * `wkb_bytes`      – Study area geometry encoded as Well-Known Binary.
#' * `res`            – H3 resolution (0 = coarsest, 15 = finest).
#' * `containment`    – One of `"intersect"`, `"centroid"`, `"boundary"`, `"covers"`.
#' * `n`              – Desired sample size.
#' * `global_seed`    – Reproducibility seed (passed as f64 from R; values above
#'                      2^53 lose precision — prefer seeds within that range).
#' * `area_correction`– If `false` (default), all H3 cells have equal inclusion
#'                      probability pi_i = n / N. Cell areas vary by up to ~1.9x
#'                      across the icosahedral projection; this is ignored in the
#'                      sampling step but can be corrected at the estimation stage
#'                      using the returned `area_m2` and `ip` columns.
#'                      If `true`, rejection sampling is applied so that each cell
#'                      is accepted with probability area_i / max_area, making the
#'                      effective inclusion probability proportional to area:
#'                      pi_i = n * area_i / sum(area). A pre-pass over the coverage
#'                      is required to find the maximum cell area, so this mode
#'                      incurs roughly 2x the runtime of the default mode.
#'
#' # Returns
#' A `data.frame` with four columns ordered by ascending sort key (GRTS order):
#' * `cell`     – H3 cell identifier as a lowercase hexadecimal string.
#' * `sort_key` – GRTS sort key as a zero-padded 16-character lowercase hex
#'                string. Zero-padding ensures correct lexicographic ordering
#'                on the R side (e.g. for merging tile results).
#' * `area_m2` – True area of the sampled cell in m².
#' * `ip`      – Inclusion probability ip_i of the sampled cell:
#'                  area_correction = false: ip_i = n / N  (constant)
#'                  area_correction = true:  ip_i = n * area_i / sum(area)
#'
#' Design-based estimators using the returned columns:
#'   HT total:   T_hat   = sum(y_i * area_m2_i / ip_i)
#'   Hajek mean: mu_Hajek = sum(y_i * area_m2_i / ip_i) / sum(area_m2_i / ip_i)
#'
#' The returned `data.frame` also carries the following design attributes:
#' * `n_cells`        – Total H3 cells N covering the study area.
#' * `sum_area_m2`    – Sum of all cell areas in m².
#' * `n`              – Requested sample size.
#' * `resolution`     – H3 resolution used.
#' * `containment`    – Containment mode used.
#' * `area_correction`– Whether area-proportional sampling was applied.
#' @noRd
grts_sample_from_wkb <- function(wkb_bytes, res, containment, n, global_seed, area_correction) .Call(wrap__grts_sample_from_wkb, wkb_bytes, res, containment, n, global_seed, area_correction)

#' Pre-computed cells -> Sample
#' @noRd
grts_sample_from_cells <- function(cell_ids_bincode, n, global_seed, area_correction) .Call(wrap__grts_sample_from_cells, cell_ids_bincode, n, global_seed, area_correction)


# nolint end
