# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_h3sampling_wrappers", use_symbols = TRUE, package_name = "h3sampling")

#' @usage NULL
#' @useDynLib h3sampling, .registration = TRUE
NULL

#' Generate a GRTS (Generalized Random Tessellation Stratified) sample of H3
#' cell indices covering a polygon.
#'
#' # Arguments
#' * `wkb_bytes`  – Study area geometry encoded as Well-Known Binary.
#' * `res`        – H3 resolution (0 = coarsest, 15 = finest).
#' * `containment`– One of `"intersect"`, `"centroid"`, `"boundary"`, `"covers"`.
#' * `n`          – Desired sample size.
#' * `global_seed`– Reproducibility seed (passed as f64 from R; values above
#'                  2^53 lose precision — prefer seeds within that range).
#'
#' # Returns
#' A `data.frame` with three columns, ordered by ascending sort key (GRTS
#' visiting order):
#' * `cell`     – H3 cell identifier as a lowercase hexadecimal string.
#' * `sort_key` – GRTS sort key as a zero-padded 16-character lowercase hex
#'                string. Zero-padding ensures correct lexicographic ordering
#'                on the R side (e.g. for merging tile results).
#' * `area_m2` – True area of the cell in m². Because GRTS samples cells
#'                with equal inclusion probability (π_i = n / N), area is NOT
#'                part of the sampling mechanism. It enters only at the
#'                estimation stage: to estimate a population total T, scale
#'                each observation y_i by its cell area A_i and divide by π_i:
#'                  T_hat = Σ (y_i * A_i) / π_i
#'                For the Hájek mean estimator the π_i terms cancel and the
#'                result is simply an area-weighted average of the y_i values.
#'
#' The returned `data.frame` also carries the following attributes which
#' provide the quantities needed to reconstruct any design-based estimator:
#' * `n_cells`     – Total number of H3 cells N covering the study area.
#'                   Used to compute π_i = n / N.
#' * `sum_area_m2`– Sum of all cell areas in m² (i.e. the approximate
#'                   area of the study area as seen by the H3 grid).
#' * `n`           – Requested sample size.
#' * `resolution`  – H3 resolution used.
#' * `containment` – Containment mode used.
generate_grts_sample <- function(wkb_bytes, res, containment, n, global_seed) .Call(wrap__generate_grts_sample, wkb_bytes, res, containment, n, global_seed)


# nolint end
